import numpy as np
from sklearn.cluster import KMeans
import joblib
import os

class FraudSyndicateClustering:
    """
    Uses K-Means clustering on the latent embeddings generated by the PyTorch GraphSAGE model.
    By clustering the 16-dimensional embeddings, we can group mathematically similar accounts
    into 'Syndicates' (Fraud Rings) even if they haven't explicitly transacted with each other.
    """
    def __init__(self, n_clusters: int = 5, model_path: str = "kmeans_syndicate.joblib"):
        self.n_clusters = n_clusters
        self.model = KMeans(n_clusters=n_clusters, random_state=42, n_init='auto')
        self.is_trained = False
        self.model_path = model_path

    def train_clusters(self, embeddings: list[list[float]]):
        """
        Trains the K-Means model on a batch of PyTorch GNN embeddings.
        """
        if not embeddings or len(embeddings) < self.n_clusters:
            raise ValueError("Not enough embeddings to form clusters.")
            
        X = np.array(embeddings)
        self.model.fit(X)
        self.is_trained = True
        self.save_model()

    def predict_syndicate(self, embedding: list[float]) -> int:
        """
        Assigns a new account's embedding to a known fraud syndicate cluster.
        Returns the cluster ID.
        """
        if not self.is_trained:
            self.load_model()
            
        if not self.is_trained:
            # Fallback mock cluster if model isn't trained yet
            return np.random.randint(0, self.n_clusters)
            
        X = np.array([embedding])
        cluster_id = self.model.predict(X)[0]
        return int(cluster_id)

    def save_model(self):
        joblib.dump(self.model, self.model_path)

    def load_model(self):
        if os.path.exists(self.model_path):
            self.model = joblib.load(self.model_path)
            self.is_trained = True
