import io
import hashlib
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from docx import Document
from docx.shared import Pt, Inches

class ExportEngine:
    """Handles generation of official Court Export Documents (PDF, DOCX)"""

    @staticmethod
    def _generate_digital_seal(case_data: dict) -> str:
        """Generates a SHA-256 Cryptographic Hash Seal for Document Authenticity"""
        content = f"{case_data.get('case_number')}_{case_data.get('total_amount')}_{case_data.get('suspect_count')}_{datetime.utcnow().isoformat()}"
        return hashlib.sha256(content.encode()).hexdigest()

    @staticmethod
    def generate_fir_pdf(case_data: dict, transactions: list) -> io.BytesIO:
        """
        Generates a PDF Draft First Information Report (FIR).
        Returns a BytesIO stream.
        """
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=72, leftMargin=72, topMargin=72, bottomMargin=72)
        
        styles = getSampleStyleSheet()
        styles.add(ParagraphStyle(name='CenterTitle', parent=styles['Heading1'], alignment=1, spaceAfter=20))
        styles.add(ParagraphStyle(name='SignatureHash', parent=styles['Normal'], fontSize=8, textColor=colors.gray, alignment=1))
        
        Story = []
        
        # Header
        Story.append(Paragraph("FIRST INFORMATION REPORT (FIR) DRAFT", styles['CenterTitle']))
        Story.append(Paragraph("Generated by FraudLens AI Intelligence Platform", styles['CenterTitle']))
        Story.append(Spacer(1, 12))
        
        # Case Details Table
        Story.append(Paragraph("1. Case Details", styles['Heading2']))
        case_info = [
            ["Case Number", case_data.get('case_number', 'N/A')],
            ["Title", case_data.get('title', 'N/A')],
            ["Status", case_data.get('status', 'N/A').upper()],
            ["Priority", case_data.get('priority', 'N/A').upper()],
            ["Total Fraud Volume", f"INR {case_data.get('total_amount', 0):,.2f}"],
            ["Victim Count", str(case_data.get('victim_count', 0))],
            ["Suspect Count", str(case_data.get('suspect_count', 0))],
            ["Generated On", datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")]
        ]
        
        t = Table(case_info, colWidths=[150, 300])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), colors.lightgrey),
            ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, -1), 'Helvetica-Bold'),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
            ('GRID', (0, 0), (-1, -1), 1, colors.black)
        ]))
        Story.append(t)
        Story.append(Spacer(1, 20))
        
        # Narrative Description
        Story.append(Paragraph("2. Description of Incident", styles['Heading2']))
        Story.append(Paragraph(case_data.get('description', 'No description available.'), styles['Normal']))
        Story.append(Spacer(1, 20))
        
        # Evidence / Transactions
        Story.append(Paragraph("3. Flagged Transaction Ledger", styles['Heading2']))
        txn_data = [["Ref", "From", "To", "Amount"]]
        for txn in transactions[:20]: # Limit to 20 for the brief
            txn_data.append([
                str(getattr(txn, 'transaction_ref', 'N/A'))[:10] + '...',
                str(getattr(txn, 'from_account', 'N/A')),
                str(getattr(txn, 'to_account', 'N/A')),
                f"{float(getattr(txn, 'amount', 0)):,.2f}"
            ])
            
        if len(transactions) > 20:
             txn_data.append(["...", "...", "...", f"... and {len(transactions) - 20} more"])
             
        t_tx = Table(txn_data, colWidths=[100, 150, 150, 80])
        t_tx.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.darkblue),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('GRID', (0, 0), (-1, -1), 1, colors.black)
        ]))
        Story.append(t_tx)
        Story.append(Spacer(1, 40))
        
        # Digital Seal
        seal = ExportEngine._generate_digital_seal(case_data)
        Story.append(Paragraph(f"CRYPTOGRAPHIC SEAL: {seal}", styles['SignatureHash']))
        Story.append(Paragraph("This document is dynamically generated from raw database evidence. Altering this document invalidates the cryptographic seal.", styles['SignatureHash']))
        
        doc.build(Story)
        buffer.seek(0)
        return buffer

    @staticmethod
    def generate_chargesheet_docx(case_data: dict, transactions: list) -> io.BytesIO:
        """
        Generates an editable Word Document (DOCX) Charge Sheet Draft.
        Returns a BytesIO stream.
        """
        doc = Document()
        
        # Header
        doc.add_heading('CHARGE SHEET DRAFT', 0)
        doc.add_paragraph('Generated by FraudLens AI Intelligence Platform').alignment = 1
        
        # Basic Info
        doc.add_heading('1. Case Details', level=1)
        p = doc.add_paragraph()
        p.add_run('Case Number: ').bold = True
        p.add_run(f"{case_data.get('case_number', 'N/A')}\n")
        p.add_run('Status: ').bold = True
        p.add_run(f"{case_data.get('status', 'N/A').upper()}\n")
        p.add_run('Total Fraud Volume: ').bold = True
        p.add_run(f"INR {case_data.get('total_amount', 0):,.2f}\n")
        
        # Narrative
        doc.add_heading('2. AI Investigation Summary', level=1)
        doc.add_paragraph(case_data.get('description', 'No description available.'))
        
        # Suspects Table (Mocked from transactions for docx)
        doc.add_heading('3. Key Suspect Accounts Identified', level=1)
        
        suspect_accs = set()
        for t in transactions:
             suspect_accs.add(str(getattr(t, 'to_account', 'N/A')))
             
        table = doc.add_table(rows=1, cols=2)
        table.style = 'Table Grid'
        hdr_cells = table.rows[0].cells
        hdr_cells[0].text = 'Account Number'
        hdr_cells[1].text = 'Role'
        
        for acc in list(suspect_accs)[:10]:
            row_cells = table.add_row().cells
            row_cells[0].text = acc
            row_cells[1].text = 'Suspect / Beneficiary'
            
        doc.add_paragraph('\n')
        
        # Digital Seal
        seal = ExportEngine._generate_digital_seal(case_data)
        doc.add_paragraph(f"CRYPTOGRAPHIC SEAL: {seal}").style = 'Intense Quote'
        
        buffer = io.BytesIO()
        doc.save(buffer)
        buffer.seek(0)
        
        return buffer
